AppointmentSchedule/Models/Client.cs
using System.Collections.Generic;

namespace AppointmentSchedule.Models
{
    public class Client : Person
    {

        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}

AppointmentSchedule/Controllers/AppointmentController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AppointmentSchedule.DAL;
using AppointmentSchedule.Models;
using AppointmentSchedule.ViewModels;

namespace AppointmentSchedule.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private AppSchContext db = new AppSchContext();

        // GET: Appointment
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var appointments = db.Appointments.Include(a => a.Client).Include(a => a.Worker);
            return View(appointments.ToList());
        }

        // GET: Appointment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: Appointment/Create
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult Create(int? workerId, int? clientId)
        {
            // All clients sorted by FirstName and LastName
            var clients = db.Clients
                .OrderBy(c => c.FirstName)
                .ThenBy(c => c.LastName)
                .ToList();

            if (clientId.HasValue && clients.Any(c => c.ID == clientId.Value))
            {
                ViewBag.ClientID = new SelectList(clients, "ID", "FullName", clientId);
            }
            else
            {
                ViewBag.ClientID = new SelectList(clients, "ID", "FullName");
            }


            // Active workers only, sorted by FirstName and LastName
            var activeWorkers = db.Workers
                .Where(w => w.IsActive)
                .OrderBy(w => w.FirstName)
                .ThenBy(w => w.LastName)
                .ToList();

            if (workerId.HasValue && activeWorkers.Any(w => w.ID == workerId.Value))
            {
                ViewBag.WorkerID = new SelectList(activeWorkers, "ID", "FullName", workerId);
            }
            else
            {
                ViewBag.WorkerID = new SelectList(activeWorkers, "ID", "FullName");
            }

            return View();
        }

        // POST: Appointment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult Create([Bind(Include = "ID,WorkerID,ClientID,Status,AppointmentDateTime,LengthInHours,TextBox")] Appointment appointment)
        {
            if (ModelState.IsValid && db.Workers.Any(w => w.ID == appointment.WorkerID && w.IsActive))
            {
                db.Appointments.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = appointment.ID });
            }

            ViewBag.ClientID = new SelectList(db.Clients.OrderBy(c => c.FirstName).ThenBy(c => c.LastName), "ID", "FullName", appointment.ClientID);
            ViewBag.WorkerID = new SelectList(db.Workers.Where(w => w.IsActive).OrderBy(w => w.FirstName).ThenBy(w => w.LastName), "ID", "FullName", appointment.WorkerID);

            return View(appointment);
        }

        // GET: Appointment/Edit/5
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientID = new SelectList(db.Clients.OrderBy(c => c.FirstName).ThenBy(c => c.LastName), "ID", "FullName", appointment.ClientID);
            ViewBag.WorkerID = new SelectList(db.Workers.Where(w => w.IsActive).OrderBy(w => w.FirstName).ThenBy(w => w.LastName), "ID", "FullName", appointment.WorkerID);

            return View(appointment);
        }

        // POST: Appointment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult Edit([Bind(Include = "ID,WorkerID,ClientID,Status,AppointmentDateTime,LengthInHours,TextBox")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = appointment.ID });
            }
            ViewBag.ClientID = new SelectList(db.Clients.OrderBy(c => c.FirstName).ThenBy(c => c.LastName), "ID", "FullName", appointment.ClientID);
            ViewBag.WorkerID = new SelectList(db.Workers.Where(w => w.IsActive).OrderBy(w => w.FirstName).ThenBy(w => w.LastName), "ID", "FullName", appointment.WorkerID);

            return View(appointment);
        }

        // GET: Appointment/LimitedEdit/5
        [Authorize(Roles = "Admin,AppointmentEnd,AppointmentControl")]
        public ActionResult LimitedEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Appointment appointment = db.Appointments.Include(a => a.Worker).Include(a => a.Client).FirstOrDefault(a => a.ID == id);
            if (appointment == null)
            {
                return HttpNotFound();
            }

            LimitedEditVM viewModel = new LimitedEditVM
            {
                ID = appointment.ID,
                Status = appointment.Status,
                TextBox = appointment.TextBox,
                WorkerFullName = appointment.Worker != null ? appointment.Worker.FirstName + " " + appointment.Worker.LastName : "No worker assigned",
                ClientFullName = appointment.Client != null ? appointment.Client.FirstName + " " + appointment.Client.LastName : "No client assigned"
            };

            return View(viewModel);
        }

        // POST: Appointment/LimitedEdit/5
        [Authorize(Roles = "Admin,AppointmentEnd,AppointmentControl")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LimitedEdit(LimitedEditVM viewModel)
        {
            if (ModelState.IsValid)
            {
                Appointment appointment = db.Appointments.Find(viewModel.ID);
                if (appointment == null)
                {
                    return HttpNotFound();
                }

                appointment.Status = viewModel.Status;
                appointment.TextBox = viewModel.TextBox;

                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = appointment.ID });
            }

            return View(viewModel);
        }

        // GET: Appointment/Delete/5
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointment appointment = db.Appointments.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: Appointment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,AppointmentControl")]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointment appointment = db.Appointments.Find(id);
            db.Appointments.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet] 
        public ActionResult WorkerSchedule(int workerId)
        {
            Worker worker = db.Workers.Find(workerId);
            ViewBag.WorkerId = workerId; 
            ViewBag.WorkerName = worker.FirstName + " " + worker.LastName;
            return View();
        }

        [HttpGet]
        public JsonResult GetWorkerAppointments(int workerId, DateTime start, DateTime end)
        {
            //calculates timezone difference, because Json sirialization doesnt take that into account
            TimeZoneInfo israelTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Israel Standard Time");
            int timezoneToAdd = (int)israelTimeZone.GetUtcOffset(DateTime.UtcNow).TotalHours; 

            var appointments = db.Appointments
                .Where(a => a.WorkerID == workerId && a.AppointmentDateTime >= start && a.AppointmentDateTime <= end)
                .Select(a => new {
                    id = a.ID,
                    title = a.Client.FirstName + " " + a.Client.LastName,
                    start = DbFunctions.AddHours(a.AppointmentDateTime, timezoneToAdd),
                    end = DbFunctions.AddHours(a.AppointmentDateTime, a.LengthInHours + timezoneToAdd) 
                    }).ToList();

            return Json(appointments, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ClientAppointments(int clientId)
        {
            Client client = db.Clients.Find(clientId);
            if (client == null)
            {
                return HttpNotFound();
            }

            ViewBag.ClientId = clientId;
            ViewBag.ClientName = client.FirstName + " " + client.LastName;
            return View();
        }

        public JsonResult GetClientAppointments(int clientId, DateTime start, DateTime end)
        {
            TimeZoneInfo israelTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Israel Standard Time");

AppointmentSchedule/Controllers/ClientController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AppointmentSchedule.DAL;
using AppointmentSchedule.Models;
using PagedList;

namespace AppointmentSchedule.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private AppSchContext db = new AppSchContext();

        // GET: Client
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.LastNameSortParm = sortOrder == "last_name" ? "last_name_desc" : "last_name";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var clients = from c in db.Clients
                          select c;

            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(c => c.LastName.Contains(searchString)
                                       || c.FirstName.Contains(searchString) || c.PhoneNumber.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    clients = clients.OrderByDescending(c => c.FirstName);
                    break;
                case "last_name":
                    clients = clients.OrderBy(c => c.LastName);
                    break;
                case "last_name_desc":
                    clients = clients.OrderByDescending(c => c.LastName);
                    break;
                default:
                    clients = clients.OrderBy(c => c.FirstName);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));
        }



        // GET: Client/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Client/Create
        [Authorize(Roles = "Admin,ClientControl")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Client/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,ClientControl")]
        public ActionResult Create([Bind(Include = "LastName,FirstName,PhoneNumber")] Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = client.ID });
            }

            return View(client);
        }

        // GET: Client/Edit/5
        [Authorize(Roles = "Admin,ClientControl")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Client/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,ClientControl")]
        public ActionResult Edit([Bind(Include = "ID,LastName,FirstName,PhoneNumber")] Client client)  
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = client.ID });
            }
            return View(client);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppointmentSchedule/Views/Client/Create.cshtml
@model AppointmentSchedule.Models.Client

@{
    ViewBag.Title = "Create";
}

<h2>Add new client</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppointmentSchedule/Views/Client/Details.cshtml
@model AppointmentSchedule.Models.Client

@{
    ViewBag.Title = "Details";
}

<h2>Client details</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("View Appointments", "ClientAppointments", "Appointment", new { clientId = Model.ID }, null) |

    @if (User.IsInRole("Admin") || User.IsInRole("ClientControl"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) 
        @: |
    }

    @Html.ActionLink("Back to List", "Index")
</p>

AppointmentSchedule/Views/Client/Edit.cshtml
@model AppointmentSchedule.Models.Client

@{
    ViewBag.Title = "Edit";
}

<h2>Edit client</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Details", "Details", new { id = Model.ID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppointmentSchedule/Views/Client/Index.cshtml
@model PagedList.IPagedList<AppointmentSchedule.Models.Client>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Clients";
}

<h2>Clients</h2>

<p>
    @if (User.IsInRole("Admin") || User.IsInRole("ClientControl"))
    {
        @Html.ActionLink("Add new client", "Create")
    }
</p>

@using (Html.BeginForm("Index", "Client", FormMethod.Get))
{
    <p>
        Find by name or phone: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LastNameSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter})
        </th>
        <th>
            Phone Number
        </th>
        <th>Actions</th>
        <th>Appointments</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID }) 
            </td>
            <td>
                @Html.ActionLink("View Appointments", "ClientAppointments", "Appointment", new { clientId = item.ID }, null)
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>